* 论文写作
** 学术不端

   学籍处分，暂缓授予学位、不授予学位、撤销学位、注销学位证书、三年不再接收学位申请

*** 不端行为

    - 伪造实验数据
    - 编造实验数据
    - 剽窃他人成果
      没有标明出处地复制原文、段落、插图，或复述很大内容仅改变字句。
      引用较短，使用双引号；引文超过 40，单独另起一段，所有缩进 0.5 英寸
      插图，在图标题中插入引用，或获得使用许可

*** 心怀敬畏
** 学位论文写作

   说服读者你的研究是重要的，你的实验结果，推演过程，结论等是重要的。
   必须完整回答：为什么研究，怎么研究，结果是什么

*** 华科博士、硕士学位论文撰写规定

    目录只到二级标题
    摘要应该独立成文，致谢体现语言功底，这两个务必写好
    英文摘要不能直接用软件翻译，注意专业术语表达
    行间距一致，公式输入的变量和文本的区别

**** 基本要求

 - 掌握了坚实的基础理论和系统的专门知识： 体现在文献调研、国内外研究现状
 - 新的见解：理论创新，技术创新，效果提高
 - 从事科学研究工作或独立担负专门技能技术的能力：附件中的已发表论文和参与的项目（承担的工作）
 - 立论正确、推理严谨、文字简练、层次分明、说理透彻、数据真实可靠：不能拷贝改写
 - 阅读相关文献，综述部分对所读文献进行分析和综合：用自己的语言概括文献中的成果。在开始或结尾部分，一段或者两端，通过分析得出存在的问题，需要解决的问题
 - 学术术语、标点符号、缩写
 - 图要精选，切忌与文字或者表内容重复，避免没有意义的图：图的信息丰富、准确，禁忌常见图片的拷贝；过于简单的图不要；必要的说明

**** 题名

 不超过 20 个字，避免使用不常见的缩写词、字符和公式。
 多为一个句子，能表达一个完整意思，定语+主语+谓语。

 笼统，覆盖太大，冗长，一般化

 尽可能删去多余词组，避免同义词近义词连用

**** 摘要（关键字）、目录、致谢

 内容--摘要，结构--目录，表达能力--致谢

***** 摘要

 - 不必分层次：首先，其次……
 - 背景、问题、成果、意义
 - 关键词：从大到小，从领域到技术，便于文献编目与查询
 - 英文摘要：不要直接软件翻译
 标准：当审稿人需要写评语时，可以直接在摘要部分找或者复制就可以

 自含性，独立性。需要包括：目的，结论

 要求：摘要可独立发表，应有独立性和自明性，500～600 字，不含参考文献，不用例证
 英文摘要：与中文对应，使用正确时态，必要冠词不能省略（可数名次前要有冠词，名词词组后有 of 或 from，前要加冠词）

**** 引言

     - 问题的由来：目前研究的热点、存在的问题及研究工作的历史背景
     - 文献综述
       参考文献序号不能作为句子成分，移除文献需要之后，不能影响原句完整性

**** 正文
***** 绪论

 - 研究背景与意义, 国内外研究现状与分析, 研究内容与论文结构
 - 内容之间有严密的逻辑论证关系
 - 实事求是，客观真切，准确完备，合乎逻辑，层次分明，简练可读。工具等说明不需要
 - 格式：两端对齐、行间距 1.25、公式、变量与文本输入的区别

   第二章占比不能过大
   *公式应当作为句子的一个成分对待*

***** 结论

 - 包括：总结与展望
 - 研究的问题

***** 致谢

 - 敏感信息，直接用 xxx 代替
 - 避免拷贝，避免胡言乱语

***** 参考文献

 - 按需引用
 - 按顺序引用
 - 格式：国际标准
 - 类型：图书 M，期刊 J，会议论文集 C，专利 P，学位论文 D
 - 脚注：网址等信息可以用脚注代替

   标准定义：GB/T 7714-2015 信息与参考文献著录规范
   外文文献格式：APA，IEEE

***** 附录

      深入理解本文工作

*** 公式

 word 中 latex 插件：TeXsword，Aurora
 ppt 中 latex 插件：IguanaTex

** 回复审稿人
*** 回复审稿

  正确的心态成就正确的回复在回复审稿人意见之前，先庆祝一下你的研究论文已经走到同行评审这一步了吧~还要对百忙之中抽出时间来审阅你论文的审稿人们怀一颗感恩的心！
  在回复审稿人之前，先修改稿件当你准备好以专业、客观的方式处理审稿人的意见时，先和你的共同作者们讨论一下评审意见的内容，共同商量决定要接受哪些修改，反对哪些修改。修改完论文之后再开始给审稿人写回复。
  回复审稿人的意见首先，感谢审稿人花时间审阅你的稿件。然后，表明你已经解决了他们提出的所有问题。
  回应审稿人的意见并不意味着你全部按照审稿人建议的修改。而是意味着：这些建议你认真考虑过后，有的做了修改，有的没有修改但是会解释原因。
  列出所有审稿人的意见以及你对每条意见的回复。使用不同的字体或文字颜色来突出你的回答，使文本易于查看。
  2. 不要直接回复 yes 或 no。即使是被要求做一些小的修改，比如改正拼写错误的单词，你可以说“We 've corrected the typo.”。如果是更严重的错误，你还可以加上“We apologize for our error.”
  3. 尽可能让你的回复内容清晰明了。让审稿人或编辑为了找到你修改的地方而再次去阅读手稿，是不可取的。既麻烦，有可能让他们发现新的问题而增加自己工作量。所以，不要说“We’ve made the change. See page 5, line 24 of the revised paper”，而是说“We’ve changed [original text] to [edited text] (page 5, line 24)”。直接展示出来。但如果你改写了整个段落或某个部分，你可以这样回答:“We have revised the text to address your concerns and hope that it is now clearer. Please see page 5 of the revised manuscript, lines 9–20, and page 6, lines 1–20.（我们已按照您的建议修改了文本，希望现在能符合要求。参见第 5 页，第 9-20 行，第 6 页，第 1-20 行。）”
  4. 不要忽略审稿人提出的任何建议。应该对每一条意见进行回复——要么做出修改，要么拒绝修改，但是要给出拒绝的理由。
  5. 选择明智的做法：即使有时候你不同意审稿人所提出的某些微小的修改建议，但通常对于细微的修改最明智的做法是接受建议，这也能表明你虚心接受建议。
  6. 在解释你为什么不同意审稿人的建议时，措辞要委婉。为了表明你的观点，你可以使用一些补充材料，如图表和表格，但这些补充材料不能是你论文中的材料。
  7. 当审稿人不能理解你的观点时,不要以为他们是无知的。如果他们都没能理解你写的东西，就说明你没能清楚地表达你的观点，其他的读者更容易感到困惑。因此，必要时修改论文内容以使论文清晰且富有逻辑性。
  8. 要对每个审稿人的意见逐一做出回复，就好像他们是你的唯一审稿人一样。不要对一个审稿人说“Please see our answer to comment 34 of Reviewer #2”。
  9. 在最后结尾时，加上这样一句话：“We would like to thank the referee again for taking the time to review our manuscript.（再次感谢审稿人花时间来审阅我们的稿件。）”

* 疾病
** 药物

  人类的药物只是缓解因感冒病毒导致的症状而已！
  药物治疗只是帮助免疫系统消灭病原体！
  而做手术实际上是偷天换地，把生病的地方切除掉罢了，并不是治愈疾病本身！！！

*** 2020 疫情隔离期间讨论
**** 支部讨论

  - 对于世界体系过于乐观，实则脆弱

  - 对于人，过于黑暗，实则坚强

  例子：同学全家病重，无法送进医院，大家捐款帮忙送医院

  对于我们，非常好，认识到人的力量，认识到世界的不足，去努力改进吧

** 2020 新冠肺炎
* World Nature
** 原理
** 理论的使用性

 一个理论，比如说牛顿定律，能解决什么问题，不是从数学上判断的；而是我们拿着这个理论去用，和实际对上了就说明它适用，什么时候对不上就说明它不适用了，这就是它的适用范围。

 很多实际问题，是没有办法也没有必要从理论上从数学上做出完备的解释的，往往我们不一定需要了解他的机理，只需要掌握他的规律就能加以利用。

 实际上 CFD 算出来的东西要判断它是否可靠，要么能和实验对上，要么能和不同算法算的结果对上；这本质上就是寻找和掌握规律的一种方法

* humanity

人性

** 爱

真正爱过你的女孩子，城府深到你无法想象。
她可以在第一次见你的时候余光扫到你的球鞋，知道你家并不是很富裕，然后不动声色地跟你说想吃那个平价料理店，好久没吃好想念。
她可以一边和你聊天一边套出来你喜欢的女生的类型，然后拿着模板照片去调整自己的装扮，让你不知不觉看她越来越顺眼。
她可以在你不知道如何开口道歉的时候发生一堆生活里的破事请你帮忙，今天是电脑坏了明天是猫找不到了后天是自行车被偷了，等你满头大汗忙完了才发现之前为了啥事儿闹别扭的来着你已经忘了。
她可以正好路过你那里，正好多买了很多水果和零食，正好让你分给同事，让你在宿舍里被众人起哄揶揄，宣告正主身份。
她可以打着请你辅导功课的名义，天天缠着你，催着你，让你不能再在宿舍偷懒，只能陪她在图书馆攻克你那头疼的四六级。
她可以恰好生来就与你有同样的饮食习惯，听同样的歌，看同样的动漫，玩同一个游戏。
她可以恰好认得你喜欢的明星和球队，听得懂与他有关的所有段子和梗，和你一起笑的前仰后合。
她可以不要房子不要彩礼，随便你给的起什么，就等着说一句「我愿意」。
她可以在闻到你身上她没有的那款香水味的时候，不动声色的检查你所有的社交平台账号，一眼看出所有的蛛丝马迹，试探着问你，最近是不是很累，要不要一起出去旅行。
她可以搜集全所有你对他不好的证据，但是在你抱着她恳求她原谅你的时候，一键清空，当做无事发生过，让你以为你做的十分周全，不露痕迹。
在你一次又一次欺骗她之后，她终于拂袖而去，从你的世界里消失的干干净净，这个时候你才能真正明白她的城府到底有多深。

原来没有她之后，你根本找不到自己的东西，你也不知道为什么每次你需要个什么东西她三分钟就能递给你，而你自己三个月也找不到那副耳机。
你所有的亲朋好友都喜欢她，他们总是要时不时在你耳朵念叨一两句，每一次提起，你的心都好像被人凌迟处刑，你耳边响起了她的声音：呵，XXX，这就是你的报应。
你再也找不到像她那样对你的女生，原来外面的小妖精一旦选择了在一起，就会变得比她还任性，暴躁，扭曲，而且吵架起来从不主动原谅你。
原来女生例假是这么痛的，她都没教会你如何给人关心。
你们谈了这么久，从来没有为她买过一次卫生经，分不清日用和夜用，更别提加长型和轻薄型。

你不知道除了多喝热水以外还可以说什么甜言蜜语哄女生开心，原来她从来不治你，就会让你失去真正撩妹的能力。
你不知道怎么给女生拍好看的照片，什么角度的侧颜更好看，什么姿势显得腿更长，别的女生拂袖而去，只有你愣愣地站在原地。
你以前以为自己的缺点是不够有钱，她走了以后你才会明白，在你们过去的这段爱情里，你最大的错，是不够有心。

而她，从头到尾都知道这一点，却到最后都没有拆穿你。

* 自我认识
** getting things done
*** 悬而未决的事情

    任何没有找到应有的位置和恰当的存在方式的事物,都会盘踞在我们的脑海中,成为悬而未决的问题

    解决方法：
    1. 明白你的工作到底是什么
       在 org mode 的任务，加上对任务的解释，和预期
    2. 行动方案
       任务下的 todo
       经常查阅的体系中安排组织好这些行为的提示信息（项目-文件-行，文件-页，网页-行）

    org mode 尚未解决的事情
    - 悬而未决的事情，放在“工作篮”，定时清空。
      “工作篮”对应于 org mode 的什么功能？

*** 材料

    任何进入你的精神或现实世界中但尚未找到归属的事情,所有你尚未推理出理想的解决方法和下一步具体行动的事

    如果某些事情吸引了我们的注意力，那么就以“材料”的形式表现出来，例如
    - 想法，尚未确定执行过程
    - 参考资料，尚未确定用处

    掌握最新动态，广泛收集材料

    处理方式：
    将所有的“材料”百分之百地存入一些实实在在的工具篮中，把一切赶出大脑
    清空工具篮，就是完成材料的定义和解释

    材料横向管理层：
    1. 收集一切引起我们注意力的事情
    2. 加工处理后，确定它们的实质以及解决方法
    3. 组织整理得出的结论
    4. 把它们列为我们行动的选择方案
    5. 行动

*** 材料加工处理

    这是一件什么事情？
    是否需要采取行动呢？
    - 否
   	  1. 材料是一些根本没用的垃圾（垃圾箱）
	  2. 目前没用采取行动的必要，但是日后可能需要处理（日程表）
	  3. 材料具有潜在的利用价值，今后也许能派上用场（归档）
    - 是
      1. 已经承诺完成哪些工作？需要达到什么样的结果？（日程表说明）
	  2. 下一步需要采取的行动是什么？（子日程）

    设计行动方案
      1. 处理这件事。如果你能够在不到 2 分钟的时间内搞定它，那么，一旦这项工作被确定，你就应该立刻着手落实
	  2. 如果这件事指派给别人去处理，自己处理需要花费的时间不止 2 分钟，应考虑自己是否是解决这个问题的最佳人员？如果不是就干脆委托给一个合适的人员去办理
	  3. 延迟处理。如果处理时间超过了 2 分钟，自己是最佳人选，这时，自己不得不推迟行动，把它记录在某一个或者多个“下一步行动”清单上

*** 任务组织管理

    - 2 分钟内解决的工作，没必要记录
    - 已经告一段落的事，没必要记录
    - 在特定时间将发生的事（日程表）
    - 处理得越快越好的事情（下一步行动清单）
    - 等待别人去办理的事情（等待目录）

    1. 日程表
      - 在一个确切时间里采取的行动
      - 在一个确切日期里采取的行动
      - 在一个确切日期里将要获取的信息

      不再需要每日工作清单,使用下一步工作清单。
      下一步工作清单如何分类呢？
    2. 下一步清单
      - 两分钟以上时间才能完成,无需指派给其他人

    3. 备忘录
      - 不能立即落实的工作
      - 垃圾
      - 孵化器
      - 参考资料

*** WAITING 回顾
    - State "WAITING"    from "SCHEDULE"   <2019-10-17 Thu 10:21>

** DONE 时间管理
   CLOSED: [2020-08-03 Mon 08:56]

 计划，有意识地控制时间花费，提升效率

*** 场景

 工作计划，生活提醒

 生活事务一般颗粒度更小、可执行性更强

 工作事务需要的是，能够辅助我们思考，并寻找任务执行路径的工具

**** 工作的特点

 通过搜集信息、分析可行性路径、寻找最优解，进而把粗粒度任务拆分成具体可执行动作

 - 时间充足
 - 很少会忘记工作上的事情
 - 需要记录和梳理工作思路
 - 不具备直接执行的条件，也不能直接无脑执行

**** 生活的特点

 - 缺少时间，容易遗忘和拖延
 - 不需要做进一步的拆分，本身就是一件可以直接执行的事情

*** 方法

 - 把简单问题复杂化，不推荐  [效率]
 - 冗长的设计流程耗费了使用者太多的心智 [效率]
 - 需要做决定的地方太多，需要从总体做综合考量的地方太多。（对于需要锻炼自己思考能力，是一个很好的方式） [效率]
 - 缓解焦虑，保持专注和清晰的思维有助于提高效率 [效率]
 - GTD 通过把能想到的事情快速丢到 inbox，每天检查 inbox，是为了清空大脑，如果达不到清空大脑，说明工作状态不适合 GTD  [工作状态]
 - 更好的安排事务所需的时间，更好的安排计划，远远超出一个工具的价值范畴  [方法]
 - 番茄法的核心在于提升专注力：屏蔽内部和外部干扰，并使周围一切进入自己的番茄节奏  [效率]
 - 在规定的事件内完成计划事项（起始时间 schedule 和结束时间 deadline，两者同时设置，不冲突） [方法]
 - 可以先设置 deadline，在适当的时间，设置起始时间，但 emacs 对这两个都没有提醒（不打扰） [方法]
 - 如果在规定时间内不能完成一项工作，比起花更多时间继续做，更应该设法减轻工作量 [方法]
 - 衡量一件事情是很难的 [效率]
 - 关注重要而非眼前的事（这对于每天开始计划工作的时候很重要） [方法]

**** 减少被打断的次数

 把不可预期的打断最小化，把工作最大化，在不被打断的情况下，尽可能增加番茄树。

***** 内部打断

 当意识到潜在的打断要来临时，停下来并记录时间和花费时间；或者下定决心，一定完成当前番茄时间，只是记录一个 TODO 事件。
 内部打断可以有，但花费在打断上的时间越少越好。
 记录打断，可以帮助了解自己实际工作状态，正确安排工作。
 延迟处理

***** 外部打断

 真正需要马上处理的事件相当少，推迟几个番茄时钟是完全可以的

*** 工具

 工作场景，笔记应用最广泛

 清单以事务为导向，日程以时间为导向，都和效率没有关系（emacs 清单和日历）

 管理精力比管理时间更重要

 以笔记软件为主，轻量提醒工具为辅

 结构化的工具，在输入的时候就是耗费脑力的

**** 清单

 - 关注点在：我还有什么事情要做
 - 灵活，简单
 - 缺少全局的时间感和控制感，直觉上有事情永远处理不完的挫败感
 - 任务天差地别，工作量和任务的数量没有关系

**** 日程

 - 关注点在：在特定时间段我要做什么
 - 维护起来太麻烦了
 - 计划没有变化大
 - 过于严格的时间分块，可能会打断工作状态

**** 笔记

 - 需要能够很好承载原始信息
 - 需要在原始信息加工过程中起到辅助作用
 - 工作的原始信息，不是结构化的，但笔记格式是结构化的
 - 把只言片语的工作要求，通过信息搜索、路径拟定、任务拆分等手段转化为结构清晰的可执行动作，正式多数脑力劳动者的核心价值，也是提升工作效率的关键
 - 笔记需要支持录入松散信息，有完全支持输出足够结构化的信息
 - 过程一定是连续的、需要反复推演修正的，输出应该是结构的，能够作为个人工作结果的承载与再加工（emacs 擅长）

*** 结论

 1. 分类
    - 直接处理，仅作记录或提醒
    - 复杂任务，录入笔记，直至拆分成一组和直接执行、定义明确的简单任务
    - 简单任务，需要多人协作的，录入相关系统；不需要协作的，在笔记中跟踪处理，如果有很强的时间要求，录入提醒工具
    - 个人工作任务都放在一个地方，便于回顾和检索
 2. 方法
    - 试图用提醒工具处理复杂事务，无异于负薪救火
    - 在移动端试图功能堆砌，用复杂的设计实现桌面端的工作，是得不偿失的
    - 以桌面端为主，移动端为辅：移动端适合提醒、简单记录的场景；桌面端适合处理复杂事务
    - 提醒工具应该灵活可靠（emacs 不满足），添加内容时简单，时间管理清晰（日历可以满足）
 3. 思考
    - 时间管理的核心是： *做重要的事*
    - 工具是要在自己需要的时候帮自己一把：笔记辅助思考，清单和日程管理帮助自己不要忘记和忽略并提供索引。
    - 做规划是自己最主要的任务
    - 符合本能、直接很重要，意味着不需要消耗额外的精力
    - 单纯一种方法都没法解决所有效率问题
 4. 工具链
    - emacs 可以实现笔记、清单、日程的所有功能
    - emacs 提醒功能很弱，起始和终止时间没有提醒（有好处也有不足）
    - emacs 太庞杂了，需要把工作和生活分开，可以用日历来提醒生活，可以两者又如何把信息融合在一起呢？

** 怎么认识自己
*** 尽量客观、全面地阐述清楚认清自己地六大角度

    - 你的三观
    - 你的行为倾向 N
    - 你的梦想（欲望）
    - 你的先天条件
    - 你的能力边界
    - 你的所处环境

    关于世界观，推荐阅读《世界观：现代人必须要懂地科学哲学和科学史》

**** 认清自己的三观

     最近这段时间特别巧，正好碰到两位同学同时换工作，而且都不太顺心。两人都是先裸辞再找工作地，花了一个月投了 300 多份简历却连面试邀请都没接到几个，有限的几个面试也很糟心，所以很是受挫。
     但两人面对挫折的反应却截然不同。一位说：“今年的运城不太好， 找个时间去寺庙里拜一下”；另一个却说“这次换工作太大意了，不应该先辞职再找工作的，一旦不顺心心态就急了，下次还是要先找好作再离职”。
     他们两人的反应就体现了不同的世界观是如何影响我们的态度和行为的。

 #+begin_quote
 第一位的世界观是相信世上有佛，而且佛在控制者人的运程，于是碰到问题她会想着去拜佛以改运；
 第二位的世界观则没有体现出对佛或其它超自然存在的信仰，因此碰到问题她会更多去找具体的原因。
 #+end_quote

 世界观与人生观、价值观一起被称为三观，它们决定着我们看待世界、看待人生以及看待事物价值的根本态度。

 1. 世界观：世界观是一个人对世界总的看法和根本观点，它影响着你的人生观和价值观。
    比如，柏拉图的哲学体系就是构建在地球是宇宙中心这个世界观基础上的。
    再比如，一个相信世界是由上帝创造的人，跟一个纯粹的唯物主义者相比，两者眼中的世界是大不相同的，因此他们的人生观、价值观也会有很大的差异。
 2. 人生观：人生观是一个人对人生的看法，也就是对于人类生存的目的、价值和意义的看法。
    比如，有人的世界观是“人生在世，吃喝二字”，也就是要过得轻松快乐。有人的人生观则是“为下辈子或下几辈子修炼”或“要青史留名”。
    *这些人生观就是世界观在看待人生上的体现*，比如“为下辈子或下几辈子修炼”的人生观就是“相信世间有佛”的世界观的体现。
 3. 价值观：价值观是一个人对事物价值的总的看法和根本观点，他一方面表现为价值取向、价值追求；另一方面表现为判断事物有无价值及价值大小的评价尺度和准则。
    比如，有人视金钱为最高的价值追求，而有人则视金钱为身外之物甚至视为粪土。
    因此，要正确认清自己，你就要花点时间来捋一下自己的三观，这样你就会知道为何你会持有某种观念，为何你会认为有些人讲的好有道理，为何你认为胡说八道的人却有很多人追捧等等。

    想要进一步确立自己的世界观，推荐阅读《世界观：现代人必须要懂的科学哲学和科学史》

**** 认清自己的梦想（欲望）

     我儿子刚上幼儿园小班，我问他：你长大后的梦想是什么？他说想做一名厨师。
     我又问他：为什么你想做一名厨师呢？他回答：这样我就可以做很多好吃的给自己吃呀。
     梦想就是现在想未来的事，所以哪怕是很小的小孩子，心里也是有梦想的，虽然听起来很搞笑，但这却很好地体现了他当下的某个欲望。
     梦想的本质是一个人的三观在奋斗目标（欲望）上的集中表现,之所以要将梦想单独拿出来讲清一番，目的在于要确认下你的梦想是否跟你的三观一致。
     人是一种容易从众的社会性动物，很多时候我们自以为的梦想不过是一个跟风的目标而已。
     比如，在元朝和明朝绝大多数读书的梦想就是为了中科举做官。
     改革开放初期，在造导弹不如卖茶叶蛋的重商氛围下，很多人的梦想就是做生意赚钱。
     以这些年很热的创业梦想为例。如果你的创业梦想还是在“大众创新，万众创业”的浪潮下产生的话，你就需要好好捋一捋，你的创业梦只是跟风，还是你的的三观的体现呢？
     如果是前者的话，你就可以好好思考下，是否还有其它更符合你三观的梦想存在呢？

**** 认清自己的行为倾向

     春节的时候带小孩在景点玩，那人叫一个多。稍微热门一点的项目就是两排长长的人龙，排上一个小时都不一定能轮上，几乎人人都排的心焦气躁的。
     我记得在排队等缆车的时候，几乎要排到我们的时候，有位妈妈拉着小孩就插队到我们前面了，边插队还边说“我们之前就排队了，刚刚是带小孩去洗手间了”。
     我下意识的反应就是退后避让。结果排在我后面的一个面色潮红的姑娘不干了，尖着嗓子就喊了“怎么这么没素质，不排队呢！”
     *在长时间排队耐心几乎耗尽的情况下，这是人的行为几乎就是本能的行为倾向了*。
     我的行为倾向是避让，而后面姑娘的行为是攻击。
     我们很多行为都是下意识的，比如，有人坐着晃腿，有人爱清净独处，有人爱发语音不爱写文字。
     这类行为倾向是很难控制的，因为你还没意识到它就已经发生了。
     因此你要先用各种评测，立体地了解下自己的行为倾向，这样你才有可能在某些情景下对这类行为提前做干预。

     为何一定要了解自己的行为倾向呢？原因有三个：

     1. 你可以清楚你在不受控制的状态下，最有可能形成怎样的态度，以及产生怎样的行为。
     2. 有条件的情况下，你可以尽量选择更适合你行为倾向的工作或社会角色，这样你花费更少的精力却可以做得更好。
     3. 你会更愿意调节自己在具体情景下的行为，因为你已经知道自己的某些行为属于下意识的行为倾向，这样调节起来你的心理障碍会更小。

 行为倾向可通过一些性格或人格评测工具来了解，目前市面上流行的评测工具主要有 MBTI、DISC、HBDI 等等，这些评测都不够严谨科学，有较大的概率偏差，但对了解自我的行为倾向还是有一定帮助的。

**** 认清自己的先天条件

     篮球是一项看身高的运动，像 CBA 球员（中国职业篮球联盟）的平均身高是 2.01 米，NBA（美国职业篮球联盟）球员 e 平均身高也接近 2 米。
     在这么一个长人林立的圈子里，身高不足一米七的人参与进来会怎么样呢？
     像 NBA，历史上身高不足一米七的只有九个人（还都是上世纪九十年代之前的，2000 年之后的一位都没有），其中最出类拔萃的斯波特韦伯（1米 68）职业生涯均就 9.9 份 2.1 篮板和 5.3 助攻，更其他身高正常的 NBA 球星动辄场均 20 多分相比，还是失色不少的。
     这就是先天条件的影响：如果你的先天条件不适合某个领域，你再励志，再出类拔萃也无法成为这个领域的顶尖人才。
     因此，在了解了你的态度和意识层面的三观、梦想、行为倾向后，你还要认清你客观的先天条件，在可能的条件下选择更适合你的先天条件的领域发展。
     这些先天条件主要包括你的性别、身高、相貌、肤色等等。

**** 认清自己的能力边界

     如果我请你徒手举起一个 150 斤中的麻包，只要举起来的话，我就给你一万块钱，你是不是可能会来挑战下？但如果我请你举起一个五百斤重的麻包，你还会接受这个挑战吗？
     我相信，哪怕我给你五百万你也不会接受。这两个挑战到底有什么不同呢？
     区别就在于前一个 150 斤的挑战还在你的能力或者能力成长边界内，你努力努力还是有可能做到的；但后一个 500 斤的挑战已经完全超出你的能力成长边界了，你在努力也是不可能做到的。
     在这个举例里，举重能力的能力边界因为相对比较清楚（普通人大概能举起自己体重 60%～100%的重量，经过锻炼的人则可以举起比自己体重重 115%～200%的重量），因此你会放弃对 500 斤举重的挑战。
     但在现实中，不少事情都是对很多种能力的综合要求，因此很多人就难以知道这件事是否已经远远超过了自己的能力成长边界。
     还以创业为例。
     创业是一个对人的综合能力要求很高的事，特别是中国经济从粗放式增长的时期进入到精细化增长的时期后，除了关系国计民生的部分领域外，大多数领域都已经进入了充分市场化竞争阶段，这种阶段下的创业要求远远高于之前改革开放初期靠资源、靠胆量、靠政策的创业要求。
     但大多数在选择创业时，只看到了创业可能带来的好处，却未评估创业是否超过了自己的能力成长边界。
     因此，我们还需要认清自己的能力以及能力成长边界，这样才不会作出挑战 500 斤举重的事。
     如何认清自己的能力及能力成长边界呢？
     一个很好的方法就是构建成是自己的能力树和知识体系。

**** 认清自己的所处环境

     三观、梦想、行为倾向、先天条件以及能力边界，这五项都是针对自己，往内看的。
     要认清自己，除了往内看，还要往外看，这就是认清自己所处的环境。
     举个例子
 #+begin_quote
 在中国以世袭制为主的两晋时期，一个平民家庭的孩子，有没有可能通过学富五车称为三公九卿呢？
 就历史记载来看，绝无可能
 首先，平民家庭的孩子要做到学富五车就很艰难了，但即使有人突破了这一点，在官员世袭的制度下，想改变先天出身成为三公九卿，那也是难如登天的一件事。
 这就是环境对人的限制。
 #+end_quote

 自然环境会限制你的体验和活动范围；时代环境会限制你的视野和影响；你的诚征环境会影响你的三观和行为倾向；你所处的阶层环境会限制你的成长高度。
 人最大的无力感，根源就来于超出环境上限的期待。
 所以，认清自己所处的环境后，认命，不做超出环境上限的期待，这样本身不会去执念于你得不到的东西，从而也就不会那么焦虑了。

 最后，人之所以会焦虑，核心的一点就在于发现自己对未来得 消极变化无能无力。
 这种无能无力源于三点
 #+begin_quote
 梦想（欲望）与自己的三观不符，也就是追逐的目标对自己而言是消极的
 梦想（欲望）超出了自身的先天条件、能力边界以及所处环境限制
 自己不知道自己该做什么、能做什么以及可以怎么做
 #+end_quote

 通过认清自己的三观、梦想（欲望）、行为倾向、先天条件、能力边界以及所处的环境，你就更能够找到自己应该追逐的梦想，确定自己欲望的程度，以及清楚自己适合怎么去做。

* 评论

言行一致的咖啡：闻到的和喝到的完全一致

** 网络空间的自由 :NOTE:

 [2020-09-24 Thu 09:45]
 作为一个技术人员，最好的形式，当然是利用自己的技术能力来让这个世界变得更好一些，然而这个世界的复杂性有很大一部分其实来自于人性的复杂，在行动的同时，我觉得，我们也应当进行更多的思考和讨论

 互联网接入权：物理上接入互联网； 拒绝受限的局域网络
 言论自由权利：脱离对垄断平台（如微信）的依赖，在恶劣环境中隐匿自己
 隐私和安全权：

* 人工智能
** how to discuss AI

 1. problem
 2. idea: 算法，特征
 3. motivation: 创新点:对旧方法的改进，对新领域的探索
 4. dataset-->structure-->loss value
 5. evaluation

** 智能家具
*** 中控系统
*** 触控系统
*** 灯光系统
*** 窗帘系统
*** 暖通系统
*** 影音娱乐系统
*** 安防系统
*** 网络系统
* 超算
** 超算-广州
*** 试用

- [ ] 用户单位盖章？我们不能返校。
- [ ] 虚拟机只能最大 24 核吗？如果需要更多核，怎么选择？
- 32 64G
- [ ] 可以随意安装其它软件吗？fensap ice 盗版？
- [ ] 时长计算和收费。使用时长如何计算？连续计时还是使用计时？怎么收费？使用前收费还是使用后收费？可以暂停和续订吗？
- 镜像安装
- [ ] 软件费用怎么算？
- [ ] 其它费用。内存，存储空间，网络收费吗？如何租用？
- [ ] 申请表中“天河星光”账号是什么？
- [ ] 费用预估。600h * 100 * 0.1 = 6000(6k)
- 1T 存储

桂博，广州超算这方面，我把我们昨天讨论的一些问题问清楚了。1. 申请表的盖章可以不用。2. 计算资源最高配置 32 核 64G 内存 1T 存储，更高配置需要进一步申请。3. 系统可以是 win 或者 linux。 4. 软件可以自己装，自己为版权问题负责。 5. 只能连续使用，创建资源开始计时，释放资源停止计时。中间可以随时释放资源随时创建。 6. 没有额外收费，按时计算 0.1/核/小时，

天津超算中心
65375552
- 版权
65375553
硬件环境
账号： 1 个星期
系统： windows 没有，linux 使用效率高
收费： 1.5
核： 弹性控制
包年： 100 核 28 核/28G 内存/结点
1 个结点（28 核） 1 年 2.8 万
2 个结点（56 核） 1 年 5.6 万
3 个结点（84 核） 1 年 8.4 万
4 个结点（112 核） 1 年 9.9 万

* 槽点
** 槽点
*** 西游记孙悟空前期战力惊人，后期战力崩坏

 猴子的最大特点就是猴性，跳脱、任性、好玩、不守规矩、不靠谱、乱来，很多大事上，他都觉得是没心没肺没皮没脸闹着玩，比如欺负龙王，比如要当齐天大圣，比如偷桃子。所以是“闹”，不是“反”。

 战斗风格：正面战斗力很强，但主要是不会被击败；缺少速胜强敌的手段，主要是缺少相应的法宝。更多的是才有技巧性手段取胜；技能全面，特别是逃脱技能、潜行技能非常强大。

 取经的关键问题，不是要把哪个妖洞破坏掉，也不是正面战胜那个妖王，而是要保护唐僧，他并非一个爆发力极高的人，他和顶级对手战斗，别人胜不了他，他也很难胜别人。他战胜同档次的人，一般是需要使用某种技巧的，因为他是盗贼风格。

*** 洪世贤

 1. 和品如结婚
 “我不是不喜欢你，但我跟品如认识在先”，为了责任，我也是要跟她结婚的！虽然我结婚了，可我还是爱你的啊
 2. 品如被打
 艾莉找上门打林品如，洪世贤护妻语录：你（被她打）活该！别说她想打你，连我都想揍你！
 3. 清醒渣男
 虽然我抽烟喝酒外面玩女人，但是我分得清情人是情人，老婆是老婆，我就还是个好男人！
 4. 出轨
 对，你又骚又主动，跟我从前好过的那些妖艳贱货一点都不一样，可我跟你睡一块儿，只是因为你让我觉得更新鲜刺激。
 咱们冲动归冲动，我脑子还是清醒地，这不！是！爱！情！
 我！不！爱！你！
 5. 面对逼问
 - 你明明就是爱我的，为什么不肯承认，快承认吧承认吧！
 - 不，那不是爱，明明是你勾引我的，我被你诱惑了，我只是犯了一个天下男人都会犯的错。但是！我！不！爱！你！
 6. 面对逼婚
 如果我今天因为爱情选择了你，那么有一天我也会因为爱情抛弃你，爱情是最不靠谱的东西。为了爱情冲昏头脑，然后再去离婚结婚在离婚，永无宁日。
 况且我又没为了你茶饭不思坐立难安，没你我照样活得好好的。
 不过就是管不住下半身，何必夸张成爱！
 7. 小三
 你要当我小三可以，我照样怼你没商量
 你好骚啊
 你这个女人呐，是真够贱的
 你真是不要脸！
 人家是金婚，咱俩二婚，瞎凑啥热闹
 我不搞外遇你怎么进的洪家大门
 你休想跟我讲感情，只有我跟你讲道理的份
 你当情人可以，但是你想生孩子不行
 我有老婆，你替我生什么孩子呀？你知不知道，你跟我生的孩子，叫私生子。
 你担心她干什么？心眼那么多能饿着吗？你
 你不爱我了没关系，但我还是跟以前一样爱你-----别再跟我说这些肉麻的话了，我听着想吐

*** 会动的食物

 https://www.zhihu.com/question/274396370/answer/496237073

*** 动物啪啪啪

 https://zhuanlan.zhihu.com/p/39566249

*** 细节

 国产抗日神剧《红色》
 https://www.zhihu.com/question/63537524/answer/256179408

*** 禅师数学合集

 https://www.zhihu.com/question/65218492/answer/231777603

*** 百度推广

 加了两百多个关键词，完全没经过我同意，而且没一个关键词是我需要的，完全是他们想填啥就填啥。推广范围是全国，所有的消费，实在开通后不到 10 秒钟内消费完的！

*** 甄嬛传毒酒博弈

 https://www.zhihu.com/question/21952421/answer/813941644

*** 回复信息

 别人能够很快速的回复我的消息，这说明了什么？
 他正在玩手机

* 场所
** 咖啡馆

 咖啡馆是这么一个地方：它有点吵，却并不喧闹；人很多，却彼此独立；拥有着浓厚的现代社会的烟火气息，但你却笃定地知道不会受到干扰；它提供给你一种观察的机会：你可以看到许许多多的人，但你知道无需跟他们发生联系。
 它在私人空间和公共空间之间微妙地取得了一种平衡：较之前者，它连接起了许多与你相似的人，把它们的日常生活、社会百态带到你的面前；较之后者，它又保证了封闭性和隐私性，身旁一尺之内是你的领地，别人会默契地避让而不需要你说些什么，这令人很舒服。
 在沉默中沉浸太久，会容易陷入幻觉，觉得整个世界只你一人。觉得过于安静，疑心时间已经停滞。直到窗外的蝉鸣声使你回过神来，看见买菜的人从窗外走过，听见楼下传来唠嗑和闲聊的声音，你才开始感受到这种扑面而来的、熟悉而陌生的生活气息。

* 思维
** 思维

 1. 墨菲定律如果有两种或两种以上的方式去做某件事情，而其中一种选择方式将导致灾难，则必定有人会做出这种选择。解析：墨菲定律是一种心理学效应，由爱德华·墨菲提出。根本内容：如果事情有变坏的可能，不管这种可能性有多小，它总会发生。主要有四个方面:任何事都没有表面看起来那么简单;所有的事都会比你预计的时间长；会出错的事总会出错；如果你担心某种情况发生，那么它越有可能发生。
 2. 波克定理只有在争辩中，才可能诞生最好的主意和最好的决定。解析：提出者是美国庄臣公司总经理詹姆士·波克，主要内容：无摩擦便无磨合，有争论才有高论。
 3. 奥格尔维法则如果我们每个人都雇用比我们自己都更强的人，我们就能成为巨人公司。解析：它强调的是人才的重要性。一个好的公司固然是因为它有好的产品，有好的硬件设施，有雄厚的财力作为支撑，但最重要的还是要有优秀的人才。光有财、物，并不能带来任何新的变化，只有具有大批的优秀人才才是最重要、最根本的。
 4. 美既好效应对一个外表英俊漂亮的人，人们很容易误认为他或她的其他方面也很不错。解析：美国心理学家丹尼尔·麦克尼尔提出， 主要内容：印象一旦以情绪为基础，这一印象常会偏离事实。 看不到优秀背面的东西，就不能很好地解读它。也就是（以貌取人）的另外一种说法。
 5. 蓝斯登定律和一位朋友一起工作，远较在父亲之下工作有趣得多。解析：给员工快乐的工作环境，可以提高工作效率。主要内容:可敬不可亲，终可敬；有权没有威，常失权。
 6. 洛伯定理对于一个经理人来说，最要紧的不是你在场时的情况，而是你不在场时发生了什么。解析：让员工成为有工作责任的主人。主要内容：如果只想让下属听你的，那么当你不在身边时他们就不知道应该听谁的了。
 7. 刺猬理论刺猬在天冷时彼此靠拢取暖但保持一定距离，以免互相刺伤。解析：在管理学中，刺猬理论强调的就是人际交往中的“心理距离效应”。运用到管理实践中，就是领导者如要搞好工作，应该与下属保持亲密关系，但这是“亲密有间”的关系，是一种不远不近的恰当合作关系。与下属保持心理距离，可以避免下属的防备和紧张，可以减少下属对自己的恭维、奉承等行为，可以防止与下属称兄道弟、吃喝不分。这样做既可以获得下属的尊重，又能保证在工作中不丧失原则。一个优秀的领导者和管理者，要做到疏者密之，密者疏之，这才是成功之道。
 8. 托利得定理测验一个人的智力是否属于上乘，只看脑子里能否同时容纳两种相反的思想而无碍于其处世行事。解析：思可相反，得须相成。主要内容：人非圣贤，孰能无过。很多时候，我们都需要宽容，宽容不仅是给别人机会，更是为自己创造机会。同样老板在面对下属的微小过失时，则应有所容忍和掩盖，这样做是为了保全他人的体面和企业的利益。
 9. 沃尔森法则把信息和情报放在第一位，金钱就会滚滚而来。解析：你能得到多少，往往取决于你能知道多少。主要内容：要在变幻莫测的市场竞争中立于不败之地，你就必须准确快速地获悉各种情报：市场有什么新动向？竞争对手有什么新举措？……在获得了这些情报后，果敢迅速地采取行动，这样你不成功都难。
 10. 吉德林法则把难题清清楚楚地写出来，问题便已经解决了一半。解析：谁都会遇到难题，人如此，企业也是如此。在瞬间万变的环境下，怎样才能最有效地解决难题，并没有一个固定的规律。但是，成功并不是没有程序可循的。遇到难题，不管你要怎样解决它，成功的前提是看清难题的关键在哪里。找到了问题的关键，也就找到了解决问题的方法，剩下的就是如何来具体实行了。

* 休息
** 入睡
*** 调研

- [ ] Coupled electrophysiological, hemodynamic, and cerebrospinal fluid oscillations in human sleep
- [ ] Sleep increases chromosome dynamics to enable reduction of accumulating DNA damage in single neurons
- [ ] Zebrafish as an emerging model for studying complex brain disorders
- [ ] Characterization of Sleep in Zebrafish and Insomnia in Hypocretin Receptor Mutants

第一篇是 2019 年 11 月份发表的，相关的研究人员发现睡眠时血液会周期性的、大量地流出大脑，然后脑脊液会大量流入，而脑脊液会清除各种有害的代谢副产物，从而起到修复大脑的作用。

第一篇论文是在宏观层面观察到了睡眠时大脑的运行机制，后面几篇论文则是在微观层面发现了睡眠的一些好处：在对斑马鱼进行实验后，发现睡眠时神经元的 DNA 损伤在减少。

*** 入睡统计

工具：手环
统计数据： 我的作息大致上是以周为单位变化的，所以统计的是一周每一天的平均值和中位数

*** 入睡方法
**** 身体放松

  呼吸--面部--眼部--肩膀--胸部--手臂--大腿

**** 精神放松

 一旦你身体放松了，只要头脑十秒钟内没有任何活跃的想法，你就会睡着。
 不要有运动的想法

**** 外界手段

- 给自己设闹钟，晚上到点就把手机放到桌子上，绝不带到床上，然后睡觉
- 早上也定闹钟，但只是提醒自己到了起床的时间
- 晚上定时煮粥啥的，早上到点后食物的味道会增强我起来的动力

** 健身
*** 一周健身计划

 一周六练，每次一小时左右;选择 8-12 次力竭的重量;每个动作 4-5 组，每组 8~12 次;动作间休息 30 秒;组间休息 1 分钟(练腿一定要 3 分钟，避免练吐了）

**** 1 腿

 哑铃深蹲
 杠铃直腿硬拉
 杠铃箭步蹲
 器械腿屈伸
 哑铃箭步蹲

**** 2 背

 俯身杠铃划船
 引体向上
 坐姿器械划船
 高位下拉
 杠铃屈腿硬拉

**** 3 手臂

 哑铃锤式弯举
 仰卧哑铃交替弯举
 哑铃集中弯举
 站姿拉力器绳索下压
 坐姿哑铃屈臂伸
 板凳负重屈臂伸

**** 4 腹部
**** 5 肩

 坐姿哑铃推举
 站姿杠铃颈后推举
 坐姿杠铃颈前推举
 哑铃前平举
 哑铃侧平举
 哑铃俯身飞鸟

**** 6 胸

 上斜俯卧撑
 平板杠铃卧推
 平板哑铃飞鸟
 上斜杠铃卧推
 拉力器夹胸
 双杠屈臂伸

**** 7 有氧

 网球
 羽毛球

*** 减肥

 营养摄入不足，就会先消耗肌肉和水分，并不是脂肪
 一天起伏个 3~5 斤都是正常的

 要想稳定减脂，胰岛素水平必须稳定，内分泌平衡

 减脂的本质就是制造热量差

 女性基础代谢率=661+9.6×体重(kg)+1.72×身高(cm)-4.7×年龄；
 男性基础代谢率=67+13.73×体重(kg)+5×身高(cm)-6.9×年龄。
 对我而言 (- (+ (+ 67 (* 13.73 68)) (* 5 178)) (* 6.9 24))
 1725.04

 一天最好是有 300~500 大卡以上的热量差。不要一下子超过 800 大卡。

**** 饮食

 低碳水➕高蛋白（肉）➕高膳食纤维（绿叶蔬菜类）

 早餐：公式——蛋白质➕水果➕粗粮早餐：公式——蛋白质➕水果➕粗粮
 鸡蛋➕玉米➕全脂牛奶➕低糖水果
 无糖燕麦片➕鸡蛋➕低糖水果

 午餐：公式——半碗主食➕非油炸/非红烧各种肉类➕蔬菜（尽量少油）

**** 运动

 无氧为主，有氧为辅

*** 胸肌

 整体厚度足够
 上胸饱满平整
 下沿线条优美
 中缝窄长连贯

 胸肌是最容易练大的一块肌肉，但要练得好看，就有很大的难度。
 胸肌的大小与你的手臂（二头肌和三头肌）大小正相关。
 胸肌的作用大致也就是让男人穿衣可以更加饱满一些，更挺拔。

**** 训练方式

 把大重量的动作放到前面。
 针对你的弱项，应该在日常训练计划里增加额外的训练。
 尝试新动作，增加重量。
 把胸部训练放在休息日之后。

**** 平板

 沉肩，不要耸肩；肩胛骨保持收紧；小臂与地面垂直，大臂与身体呈 45 度；核心收紧，身体略微反弓；杠铃下降到乳头或上方 2cm 处；下落吸气，推起吸气；推起时肩膀不能前伸；
 主动收缩肌肉，被动控制只能该肌肉发力
 https://v.youku.com/v_show/id_XMTQzMzkyMzI5Ng==.html?spm=a2h0k.8191407.0.0&from=s1.8-1-1.2

**** 入门阶段 - 打基础

 卧推的重量一上去几个星期就增大很明显，在卧推动作里，如果没有强大的手臂，无法充分刺激胸部肌肉，也就无法让胸肌变大，也就无法保持动作的稳定性，会很危险，也无法维持强度很大的训练

 增大三头和二头

**** 冲重量 - 迅速增大阶段

 增加维度。变宽、变厚。力量快速增大。但，无分离度、无线条、无美感。
 以周为单位，一般一周练胸一次，最多练两次。

 平板卧推
 平板飞鸟
 负重俯卧撑

 每次在冲击重量之后，要用无负重俯卧撑或者轻重量器械做到力竭。

 最好能有一个朋友帮助或者一起锻炼。在一个大重量力竭之后，再帮助完成 1-3 个，效果是最好的。

 补充一些蛋白质食物，最好的选择，Salmon、Steak、鸡胸，由于大重量刺激，关节修复也是一个比较关键的营养补充点，适当吃一些，鱼油、Chia 籽、坚果有很大帮助

**** 调整阶段 - 使胸肌轮廓变美观

 这个阶段，平板杠铃卧推这个动作就请不要再练了。

 缆绳胸部下压：胸肌的外围弧度曲线
 高位推胸：上胸饱满度
 低位推胸：胸肌下沿的轮廓，渐渐出型
 双杠屈臂伸：胸肌轮廓
 飞鸟：胸肌的沟，重量增大，很快出现胸肌分离度
 哑铃卧推： 对胸肌下沿的线条，有非常好的雕刻作用

*** 拉伸
**** 肩膀

 肩膀从前往后画圈，头向下看时 5 圈，头向前看时 5 圈，头向上看时 5 圈；
 肩膀从后往前画圈

**** 三角肌

 左手握住右手手腕，保持腰不懂，向左拉伸右臂。同理右手。注意手心朝上和朝下的不同拉伸部位

**** 扩胸

 手心向上向下相对扩胸

**** 斜方肌

 手臂向上画圈

**** 背阔肌

 左臂向上，保持腰稳定，身体向右侧弯

**** 背部

 双臂向前拉住固定物，俯身拉伸

**** 腿部

 手握脚腕，向后踢；
 腿踩在椅子上，向前压

* 读书
** 读书
*** 睡前碎片阅读
**** 要求

 - 拿得起拿得起，指的是书的内容有比较有趣。也指该书的语言比较简单，不会像学术论文的语言那样烧脑。最后，该书的内容又要有一定实用性，至少能给我们增加一点谈 (bi) 资 (ge) 。
 - 放得下放得下，指的是书中每个章节内容相对较为独立。因为如果我们在睡前阅读扣人心弦，情节跌宕起伏的书（比如小说），那我们很有可能会为了追剧情，推迟入睡时间，那样第二天可能就会精神不振，那就得不偿失了。

**** 时间分配

 - 35 分钟用来阅读。阅读中我一般不做笔记，因为记笔记会阻碍我进入美好的心流状态 (flow)。
 - 10 分钟用来在回忆这 35 分钟阅读的内容。之后，我会在书的留白处写小结，以加深记忆。
 - 5 分钟用来联想。我会思考刚刚阅读的内容与我的生活有何联系，然后记下几个关键词。

**** 书目推荐
***** 传记

 - [ ] 当我谈跑步时我谈些什么
 - [ ] Becoming Steve Jobs: 乔布斯如何从曾经极度缺乏耐心，浮夸，不切实际的创业者，变成一位愿意倾听，拥有理性的创造力的商业偶像。本书重点关注的是这个 becoming 的过程
 - [ ] 压力测试：反思金融危机: 如何走出迷茫期

***** 经济

 - [ ] 牛奶可乐经济学
 - [ ] 集装箱改变世界
 - [ ] 稀缺：我们是如何陷入贫穷与忙碌的

***** 历史

 - [ ] 人类简史：从动物到上帝
 - [ ] 枪炮、病菌与钢铁 : 人类社会的命运

***** 设计

 - [ ] 设计中的设计: 无印良品艺术总监原研哉先生对于这些作品的点评
 - [ ] 创新公司：皮克斯的启示

*** 为什么要读书

 身上有着知识沉淀的气质，就感觉她像一本书，你翻不完，而且也不知道翻得是哪一页。

 显得太单薄了，单薄的就像一层纸，一眼就能看透。

 我所拥有的内涵是什么？不就是人人能脱口而出，游荡在空气中最通俗的认知吗？

 读什么书，读多少书，不是为了在什么时候去跟别人吹牛逼，有太多有意思的事和你闻所未闻的东西，不看书你根本不知道。

 有太多有意思的事和你闻所未闻的东西，不看书你根本不知道。

** 负能量作文

 真要有把牛粪写成鲜花还让人忍不住给你浇水的本事，你写什么都没问题！可你要是故意刻奇，好高骛远，连普通的材料精神都领会不了，老老实实议论文弘扬正能量，难度低，分数高。你想抨击现实讽刺人性？等你北大毕业了，有的是机会，不然只能跟我一样，在这网络平台上宣泄负能量，眼睛巴巴的盯着每一个没点赞的，仿佛七月十五穿红衣上吊的冤死鬼似的。

* 交流
** 冷暴力

 “冷战”是双向的，“冷暴力”是单向的，男生和女生对“冷暴力”的耐受程度是不同的，当男女双方都需要一段时间来思考，处于“冷战”状态时，男女对情感的需求程度是不同的，因此会有女生觉得自己被冷暴力很委屈，而男生还没意识到的情况。
 因为题主没有说明“冷暴力”具体是指什么，所以我暂且把冷暴力理解为，“当恋爱双方发生了情感危机时的沉默式应对”，来表达下自己的看法。
 一开始我对这个问题很不喜欢，因为把男生和冷暴力划在一起是很不合理的，“逼女生分手”这样的表达，把冷暴力和男生放在了一个相当危险的环境中。
 因为最近看了一部 2014 年的老剧《约会专家》，很有默契的男主女主，在遇到了一些真正触及到内心深处的伤痛，需要作出选择时，男主的沉默，使得两人的感情几乎走上了末路。据说，电视剧也设置了两个不同的结局，一个是男主在女主即将上飞机的时候，站出来挽留了女主，两个人终于表明了心迹；另一个是男主始终没能开口，放下了喇叭，女主停顿了一下，和另一个人上了飞机。这部剧优秀的地方在于，两人其实都有在为这段感情做出努力，两个人非常详细的心理描写充分展现了男女在面对很难抉择的情况是如何思考的，男主夜夜到女主楼下等待，女主主动表达了自己的立场和要求，即如果男主能在她上飞机前挽留她，她就会留下来。我为美好的结局感到大出一口气，反而不好的结局一直萦绕心头，因为沉默或者说冷战，真的影响太大了。

** 聊天
*** 闲谈的三条最基本的技能

 ①问出一个让对方能自由发挥的问题
 a.不要问一个词就可以回答的问题如：
 你常去海边度假吗？你喜欢恐怖电影吗？
 更好的问法：你喜欢去哪里度假？你喜欢哪种类型的电影？

 b.不要问太泛或太深的问题如：你对一带一路怎么看？
 更好的问法：一带一路对你们那个行业有什么影响？

 ②一问二答一问二答可以让对方轻松接下话茬。
 “你们家乡也会这么冷吗？”普通回答：“没这么冷”。
 更好的回答：“没这么冷。今年的冬天咱们这儿真是少有的冷。不过我今天穿了发热衣，最新科技，真的好像在我身上发热诶。”

 ③认真倾听，扩展再扩展。
 “上个月我刚从上海搬到深圳，这儿空气很好”。
 可以听出的信息有她是一个注重生活品质的人；上海的空气已经不让人满意了；她精心比较和选择后，来到深圳；她不会固守一个城市住到老。
 将谈话合适地扩展下去：搬到新地方，你还习惯吗？你还在哪里居住过？在哪个城市住得最久？有没有去过深圳的海滩、红树林？那儿可是天然氧吧。我在深圳住了 8 年了，你有什么特别想了解的？我能帮忙。
 扩展的本领，基于真正的倾听。

*** 开场：怎样构建一个话题

 ①用冷读者+热捧者的身份敲门冷读者展示你冷静的观察力，让这第一句破冰的话显得不唐突。热捧者就是你要展示你十足的善意，此次谈话以给对方制造愉悦为己任。
 如果有人和我搭讪，一上来就问：“你是做什么的？”那就有些唐突，而且不够温和。
 如果用“冷读者+热捧者”的身份，他应该这样说，“你讲话很有条理，你是从事培训的吗？”他短短的一句话“你讲话很有条理，你是从事培训的吗？”既有冷读，也有热捧。
 他已经冷静地观察出了我讲话时的特点，并夸赞了我有条理。我听了很高兴，既被他关注了，又被他表扬了，受关注的需求和被尊重的需求全部满足了。这就是冷读者+热捧者的身份。
 哪怕当时他冷读错了，猜错了，也没有关系。
 a.从周围的道具找话题看见对方手里端着某种饮料时，你可以说：“这个饮料看上去不错，这是什么呢？”
 你冷静地观察到他对饮料的选择，并称赞这个选择不错。
 对着会议厅里的邻座，你可以说：“你的装备真齐全。能借支笔吗？”你冷静地观察了他的物品，并称赞其“装备齐全”。
 对着咖啡馆里的邻座，你可以说：“你的这款 Macbook pro 是苹果今年出的高端款吧，我一直都想买，请教一下，这款好用吗？”你冷静地观察到他的电脑，并表示了自己的羡慕和向往。

 b.从对方身上找话题包括他的外在服饰、身材、气质、内在特质等。
 从对方的身体上找话题：“看你这挺拔的身材，常去健身吧？”从对方的个性上找话题：“这里很多人都认识您，您最有人气呢。您是从事什么工作的？”“您这么幽默，打赌您是双子座的。”“哇，您好会聊，您要是做销售绝对是个高手。”“我看您戴手表和我们不一样，在右手上，有个性。我猜您是从事创意方面的工作？”从对方的气质风度上找话题：“这双高跟鞋超有女人味。如此细高的跟儿，我肯定是走不稳的，你却驾驭得炉火纯青，是学过舞蹈吧？”
 从对方的服饰上找话题：“你这身西服相当别致合体，定做的吧？”“您的衣服搭配很有品位，您是时尚行业的吗？”“很少看见中国男士穿法式衬衣，这袖扣相当别致，我猜您是海归？”

 c.从那时那刻的状态找话题一个人当时的心情、表情，以及做一件事情时的状态是认真，还是疲惫，你只要稍加注意，就可以观察出来，并能用这个来作为话题切入点。
 “看你们聊得这么投机，猜你们认识很久了？”“我注意到你刚刚听得很认真，今天哪个嘉宾的发言你最喜欢？”“看你今天兴致很高，有啥开心事儿吗？”
 ②两个调味品让开场更有滋味：
 a.猜谜语不要问：“你从哪里来？”
 而是问：“你从哪里来？等等，让我猜猜。给我两个提示吧。”
 不要问：“你最喜欢看哪部美剧？”
 而是问：“你最喜欢看哪部美剧？等等，让我猜猜。给我两个提示吧。”
 b.诚心请教
 比如，你问对方：“你来上海多久了？”他说：“三年。”你接着说：“我刚来，正在考虑要不要留下来呢。请教一下，你最喜欢上海生活的哪些方面？”
 这一招让人觉得自己的经验和看法受到了关注，他的参与度更高。诚挚地请教，既是放低身段，也延展了话题范围，让对方更顺利地和你聊下去。

*** 交谈：把握往来的节奏

 ①推进聊天的三部曲——“说，问，说”先做个自我陈述，然后问一个开放式问题，之后再自我陈述。你发现对方穿了件漂亮的裙子，做一个称赞式的陈述：“裙子的颜色很衬你哦，这花色也很少见的。”然后问问题：“可以问一下，你在哪里买的吗？”她说：“我去年在马来西亚旅游时买的。”
 你听到了一个有价值的信息点——马来西亚。
 于是你要来做一些自我陈述，然后再问第二个问题：“我去年春节也在马来西亚。你觉得那里怎么样？”如果她开始滔滔不绝：“我超级喜欢那里，……”恭喜你，你顺利踩中她的兴奋点，这时的你静静倾听就好。如果她还是很简短地回答：“那里不错。”那么这时，你应该用自我陈述接上：“去年我们带着孩子去沙巴，发生了一件有惊无险的事。幸亏那天我们取消去环滩岛的计划。就在那条线路上，有艘游船翻了，32 小时后 20 多名中国游客才被救起。”
 ②冷场后的急救术
 a.另起炉灶比如，你可以快速地问个问题。
 “诶，问你一下，刚刚最后那个嘉宾说的区块链到底怎么理解？”你问的时候，身体可以微微前倾，向他靠近，以让这句话不显得那么突兀。
 或者，你脑子里貌似突然闪过新奇的事情，和他分享：“我今天早上在路上居然看见那种卖老式爆米花的。都 N 年没见过这玩意儿了。”

 b..正反回应正面回应，就是我和你很有共鸣；反面回应就是，我和你没有共鸣，但是我很有兴趣探究你的世界。
 比如，对方说：“我刚从罗马回来。”如果你在“罗马”这个关键词上和他有共鸣，你可以做正面回应：“我上周刚刚重温《罗马假日》。真正的罗马和电影的罗马有什么区别吗？”如果你一时在“罗马”这个关键词上和他没啥共鸣，你可以做反面回应：“我从来没有去过罗马。罗马哪些地方是很值得一游的？”

 c.扮演苏格拉底大哲学家苏格拉底擅长用问题带出他人的思考和灵感，他的这个有魔力的发问——“为什么，为什么，为什么……”有可能让一次谈话产生真正的意义，甚至让对方重新认识一次他自己。
 当然，你的发问词要多样化，比如，除了“为什么？”你还可以问“……的原因是？”或者“我不大懂你的意思，能再解释一下吗？”同时，你的发问中要加入一些自我陈述，让它不会成为一次考问。

*** 怎样驾驭闲谈的高潮和结束

 ①把交谈推向高潮的三个技巧：
 a.找到彼此的优势话题所谓优势话题，就是那些能让你滔滔不绝说上好几个小时的话题。
 如何在交谈中定位到自己的优势话题，并有技巧地跳到优势话题上有两个方法：
 <俄罗斯套娃定位法>
 俄罗斯套娃里的那个最小的娃娃就是你的优势话题，往外的每一个更大的娃娃普遍性越来越强，专业性越来越弱。
 如果你的优势话题是四川火锅，在俄罗斯套娃方法中，四川火锅是那个最小套娃，依次往外越来越大的套娃是：四川火锅 <向外> 川菜 <向外> 中式美食<向外> 烹饪艺术当大家聊到川菜、中式美食、烹饪艺术的任何时候，你都有机会跳到你的优势话题——四川火锅上。

 <原子定位法>原子中间的质子是你的优势话题，电子、中子都与优势话题相关，但专业性不见得减弱。
 在原子定位法中，四川火锅是质子，是优势话题，在它旁边的中子、电子是：四川火锅 <相关> 奇怪食材 <相关> 推荐餐馆<相关> 瑞士奶酪火锅 <相关> 川民风情当大家聊到奇怪食材、推荐餐馆、瑞士奶酪火锅、川民风情的时候，你都有机会跳到你的优势话题——四川火锅。
 Ps.让对话跳到你的优势话题上来，可以用以下过渡语：“……这个让我想起……”“说起……不得不提一提……”“你在研究……的时候，有没有听说过……”“对啊对啊，我恰巧最近读了一本关于……的书。”“说到……你看可不可以换个角度理解，……”“和……不太一样的是，……”等等
 Ps.不同人群有这么几大类优势话题：成功男人爱聊事业，普通男人爱聊老庄哲学，中年女人爱聊家庭孩子，老年女人爱聊养生，老年男人爱聊过去的辉煌，青年女人爱聊时尚，青年男人爱聊理想。
 在和这些人群谈话时，在谈话的任何时候，你都可以将话题引导到他们的优势话题上来。比如，对方是年轻女孩，你们在一个讲座茶歇中交谈。提示你一下，年轻女孩的优势话题是时尚。她说：“最近很忙，公司年底了要赶业绩，连午饭都没时间吃。”你可以说：“没时间吃午饭的美女，还是挤出了时间做指甲哟。你的指甲做得真漂亮，有推荐的美甲师吗？”

 b.交谈深入，逐层剥洋葱皮逐层深入，谈到一些触及内心的东西。
 把握“度”，按“套话，事实，观点，感受”逐层深入。
 套话——客套的话，就是社交场合那些公式化的交谈，一些讨人喜欢，别人爱听的话。这是洋葱最外面那层皮。
 在最初的两分钟，你们谈的就是套话。
 事实——再往细节里聊，这时会出现很多的私人信息，也就是属于这个人的独特的事实。
 观点——于自己身上的这些事实、信息，他一定会有自己的观点，就是说，他是如何解读的。
 感受——最深层次，是指他的爱与憎，他的情绪，他的感觉。比如有一次，我在客户的 HR 办公室里交谈，她桌上摆着全家福的照片，我称赞道：“你家宝宝长得好有灵气，你看上去真的不像有两个孩子的母亲哦。”
 这句话，就是我在用“冷读者+热捧者”的身份说社交场合的套话。我观察出她是有两个孩子的妈妈，并且既赞了她孩子的灵气，也赞了她本人的年轻和精力充沛。
 她笑道：“两个捣蛋鬼，一个六岁，一个八岁。”我接下去说：“我家也是两个孩子，昨天我还在和我先生商量，暑假是出去旅游呢，还是给他们多报几个兴趣班。你们孩子上兴趣班吗？”
 瞧，我在用“说、问、说”三部曲，推动对话。我不是直接发问，而是在问话之前，做了一些自我陈述。我的这个问题“你们孩子上兴趣班吗？”将对话引向“事实”层面。她回答说：“他们上的。姐姐上英文和芭蕾，弟弟上英文和跆拳道。”
 此时，她给了我一些独属于她的信息，我们已经进入“事实”层面。我接着说：“对，我们也都选了英文的兴趣班，小孩子语言敏感期，多接触英文总有好处。”她显得很惊讶，“戴老师，你就是教英文的，还用得着让孩子上兴趣班？”我说：“唉，我教他们，他们根本不配合。你是怎样看孩子上兴趣班这事儿的？”
 你听出来了吗？我 把对话往“观点”层面深入—— “你是怎么看孩子上兴趣班这事儿的”。她给出了一个不俗的观点：“我认为，只要找到好的老师，让孩子爱上学习，就是件好事儿。”我很感谢她如此认真地投入到我们的交谈中，我兴奋地附和道：“完全赞同！‘能否找到好老师’比‘该不该上兴趣班’更重要。嗯，我不知道别的妈妈怎样，我自从有了孩子，多多少少会有焦虑，怕自己犯养育上的错误。你呢？”我相信你已经听出来了，当我询问对方是否焦虑时，把对话导向了最深层面，“感受”层面。友谊，都是在“观点，感受”这两个层次上培育出来的。

 c.与大人物的小交谈与大人物交谈，要提前做好功课。
 第一.找一个你和他都认识的人，也就是中间人
 第二.对他本人做充分的背景调查
 第三.对他所处的行业做基本的了解，以防自己说行外话。
 加分项：你能否感知到他的难处和面临的问题，并为他提供价值。

 ②金蝉脱壳的方法：
 a.最诚实的方法：注意：在说话前，你已经配合了适度的身体语言，暗示谈话即将告一段落；记得要回顾一下你们谈过的内容，给这次对话画上圆满的句号。

 b.我要撤了，是我的错，不是你的错。而且，我是个潜力股，我愿意持续为你增加价值。

 c.两杯酒法——托辞把这杯酒送过去给朋友。

 d.假装紧急——内急，打电话，拿食物。

 e.将他托付给别人：带着他朝着你的朋友走过去，把他介绍给你的朋友。在介绍的时候，把他的亮点稍加夸张，用些溢美之词。

*** 关于闲谈，日常可做的素材积累

 ①准备三个出镜率高的故事
 a.就你们双方的共同点挖掘的故事讲述技巧：在故事中加入对话，让故事更生动。找共同之处的方法：找共同认识的人准备一些和自己家乡、学校有关的故事

 b.关于自己的故事讲述技巧：谈内心感受或谈糗事，更走心。我还经常说的自嘲故事有：我刚到美国时，进了一家干洗店，我以为是卖衣服的商店，看见漂亮衣服上面的价格标签只要$5、$10，狂喜不已，扔出 20 美元给柜员，说来 4 件。

 c.准备一个“吃、吃、吃”的故事讲述技巧：多用细节任何话题都可以聊到“吃”上，“吃”永远都有趣。你可以研究几个在宴会和鸡尾酒会上出现频率高的食物，最好亲自做过，然后聊你的制作故事。如果是一顿中餐，那么中式菜肴的典故逸事，更是最佳的聊天切入点。龙井虾仁、东坡肉、担担面、叫花鸡、麻婆豆腐，背后都是一段段好听的故事。
 ②收集跨越时空的对比素材善于做时空对比的人，聊天质量都很高。比如，你讲一个中国的人物，再对比一个国外的人物；讲一个现在的事件，再对比一个历史上的事件。你还可以对比明星，对比城市、对比教育，对比潮流，对比时代。

*** 多人聊天时，好用的技巧

 ①创造新话题的技巧：
 挑出关键人物首先，当你想创造一个新话题的时候，最怕没人接招。
 你要避免“责任扩散”的现象发生。所谓多人话局的责任扩散，指的是在场的人很多时，做出回应的责任就会被无形地扩散到这些人身上，造成人越多，扩散范围越大，个人回应你的责任就越小的现象。
 所以，你开聊时，风险最低的方式就是，挑出这个话局里的关键人物来聊。关键人物可以是组局的人，可以是这个话局里的活跃分子，可以是最有影响力的那个，也可以是那个最伶牙俐齿的，最爱讲笑话的人，又或者是那个和你最熟的人。

 ②加入聊天的技巧：发出四种声音
 a.我有见解为自己见解增加三种砝码：直接经验砝码（见解来自直接经验），学术砝码（见解来自学术专业研究），团队砝码（见解来自工作团队）

 b.我有疑虑闪电版，“不好意思，我有个简短的问题”；“抱歉打断一分钟，就一分钟，我很好奇，请问……”谦逊版，“张总，这方面您是专家，千万别笑话我问的这个问题，请问……”灵感版，“你刚刚讲的故事，让我突然想到这样一种可能。如果……请问……”

 c.我赞同，并有补充

 d.我没观点，但会归纳总结
 ③主导聊天的技巧：制造矛盾，挑动正反方，制造出不同意见相互碰撞的局面。
 当有值得讨论的观点出现时，先问有没有反对方，更能激起大家发言的欲望。最后补充一点，两个人聊天就像在打球，不要把球拽在自己手里超过 20 秒，严禁超过 40 秒。

** 技巧

[[http://liaotian.puaas.com/jiqiao/][追女孩子的聊天技巧]]
1. 那你呢，你心动了吗？  ---（回复）今天天气不错啊！
	很多事情，没必要一定给出个答案，迂回，不是敷衍，因为迂回真的很美好
	当然，懂得你迂回方式的人，可以迂回，不懂的人，迂回很显得两个人都特不对付，别扭，这时还是直接点好。

** 情话

 1. “今天怎么样？”“我这一天都过得很平淡……直到你找我聊天。”
 2. 来看星星吗 不看星星出来也行。
 3. 这一生，除了故乡，我只为你一个人写过月亮。
 4. 说不出来为什么爱你，但我知道，你就是我不爱别人的理由。
 5. 他书写的人生是我爱的故事
 6. 我之前没有爱过别人 ，你是第一个 ，我怕我做得不好， 让你觉得爱情不过如此。
 7. “月亮很亮，亮也没用，没用也亮。我喜欢你，喜欢也没用，没用也喜欢。”
 8. 对方申请做您心尖尖上的宝贝 接受请求吗
 9. 理解归理解 醋我还是要吃的
 10. 住在心里的男孩 以后一定要住到家里来。
 11. 你就是对这个世界太紧张了，有我在你不要这么紧张。
 12. 山河远阔，人间烟火。无一是你，无一不是你
 13. 等睡在你怀里时，我就不熬夜了。
 14. 我没有很好，你不嫌弃就好。你不用多好，我喜欢就好。
 15. 快点发个你的位置给我,我想知道我的心跑哪里去了。
 16. 总有些惊奇的际遇，比方说当我遇见你。
 17. 你微微地笑着，不同我说什么话。而我觉得，为了这个，我已等待很久了
 18. 遇到可爱的人生活一下子不艰难了街道也好 晚风也罢 都很甜
 19. 你是往日的情书是日落的余情未了是路人脚下不停生长的风也是我喜欢的人
 20. “想同你合影”“现在就可以啊”“不，是宽 53mm 高 35mm 的红底双人彩照”。
 21. 歌很好听 风很舒服 星星也美但更多的开心是来自你手心的温度
 22. “两个心愿：你在身边，在你身边”
 23. 希望你能越来越喜欢我，然后表现得再明显一点。
 24. 其实我真的好想你好想你，但是我很酷不会告诉你。
 25. 你是我散落在人间的日常,三三两两
 26. 晚安过后 你在睡觉 我在想你
 27. “日子被我过得太无趣了 想蹦迪 想成为你喜欢的女孩 想借着夏天的风说 我喜欢你”
 28. 直到今天我才知道，我的人生之所以漂泊就是在向你漂流而去。
 29. “晚安”“以后别和我说晚安，要说，我们一起睡觉”“你流氓，才不和你睡觉”“你想什么呢，我是说，时间上同时，不是位置上一起，就像说，夜晚到了，人类都一起进入了梦乡一样那种的一起”“好吧，让我们一起睡觉”“好的，什么时候睡一起？”
 30. 谢谢你，在这个世界的角落，找到了我。
 31. 你值得所有美好的文字来形容
 32. 我们太执着于自己的生活方式，有时候认为，只能依着一种既定的模式生存，却忘了，遇不到正确的你

* DONE 习惯
  CLOSED: [2021-03-31 Wed 11:03]

比这里的习惯，逐渐增加到 emacs habit track 中去

** 习惯

 1. 工作里的感悟、体会或者一些突然的灵感要及时记录在笔记本里
    怎么记？放哪里？
    emacs，capture note
 2. 每天要花些时间在自己感兴趣的事儿上面，哪怕只有半个小时。阅读、健身、浇花、运动、理财等等
 3. 定期给朋友发个短信，打个电话，有条件一起吃个饭。有些关系只要稍稍维护下，指不定哪天能派上用场
 4. 定期整理下财务状况。不要总是发了工资就光，你还有很多事要做
 5. 要经常写点东西
 6. 坚持固定作息，会给你一个很好的精神状态
 7. 走在不停的地方遇见不同的人，同时看见不一样的自己，会很有趣
 8. 把预计完成所需时间再×3
 9. 在你在职和离职半年以内，即使你以为自己不会用到的文件，也不要删除；文件每次做重大修改，务必保留历史版本
 10. 物品与文件相反，相信自己一年以内用不到的东西及时扔掉
 11. 每天睡觉前，把第二天要穿的衣服准备好
 12. 随时在心里对自己说：“放松一下吧亲爱的”，来个深呼吸，感到身体面部的舒展和内心的愉悦感
 13. 不要小看下班后的时间
 14. 把最常用的东西一件一件换成自己喜欢到心动的，最起码：好用的
 15. 看过的书，电影，新闻，专业信息，用自己的语言转述给身边的人，以求准确，甚至幽默有趣
 16. 建立一个“我的能量库”，里面是慢慢积累起来的让你感觉生活美好的、重拾斗志的音乐、文字、图片、视频；当你心情低落、消极的时候，打开能量库，自己治愈自己
 17. 想清楚你真正的朋友有哪些，找机会让他们知道他们在你心目中的分量
 18. 送自己一块手表，且时间比公司的快三分钟
 19. 光鲜靓丽的外表下感受到一丝猥琐
 20. 不要看对方说了什么，而是思考他为什么说这个
 21. 焦虑来自你的想象，别人对你没有预设，预设是你自己给自己的
 22. 别指望有人能理解你，降低自己对这个世界的期望
 23. 把时间从压抑自己的欲望解放到如何合理的释放自己的欲望
 24. 漂亮的外表遮挡不了空无一物的脑袋
 25. 我们要消灭贫穷，不是消灭穷人
 26. 解决问题的第一步，是承认问题的存在
 27. 为与士大夫治天下，非与百姓治天下也
 28. 世间无情无义的人又怎能以性别来分区
 29. 喜欢一个人？请她或他帮个忙吧！
 30. 喜欢一个人？请她或他帮个忙吧！
 31. 表白不是冲锋是发起的战吼，而是胜利凯旋吹响的号角
 32. 新识一个人，翻开一本书，去读她，然后试图把她放在你所知生命的历程中，离开时，她已经成了你的一页
 33. 你所接受的一切信息，构成了你的思维方式。所以，长期接受碎片信息的后果，就是让你的思维变得狭隘，难以进行复杂的思考
 34. 做事讲话，一定要有理由，不一定是为了说服别人，也不一定是为了说服自己，更多是多想多看，不跟风盲从，不理所当然地跟着习惯走，才能了解自己
	  赞同别人的建议，从我或者我们的角度出发，给出赞同的原因，比只是赞同好用太多。最少，对待建议，说我很喜欢 xxx
 35. 中文中夹英文，如果英文是常用的，会很亲切
	  认为英文能表达清楚，中文对应的表达不恰当，其实还是尝试用中文比较好
	  为了使用英文而使用英文，太傻
 36. 如果，读书不能增加智慧，旅行不能增加阅历，那么，不如取悦自己
	   当然，如果，读书，旅行，确实让自己开心，那么，另说
 37. 所以，当别人夸奖得到位时候，微笑就可以吗

* 工具
** 安卓谷歌商店

  一加 8T

  已经内置了谷歌框架和谷歌服务，在酷安安装谷歌商店，使用 ssr 连接 vpn，仍无法连接服务器。

  换用 xtunnel 的软件 v2ryng，一天免费使用，成功登陆。
  结论:软件和设置正常，是 vpn 问题

  替代工具：APKPure，正常 vpn 即可

* 工作
** DONE Find work(er)s resource
   CLOSED: [2021-03-31 Wed 11:03]
*** DONE Linkin
    CLOSED: [2020-12-23 Wed 09:32]

    update my profile on linkin: education, internship, fpga

* 桌面设备
** 日常要用的东西
* 潜力
  :PROPERTIES:
  :创建:       [2021-03-03 Wed 23:13]
  :END:

别人对你的判断，总是根据你的反应而更新的。

别人认为你有潜力，就是你每次的反应，比别人预计的要好一点

* 脑子放空
  最近，在休息时，半睡半醒之间，脑子中会闪现无数的事情：有的是回忆、反复琢磨某一片段，有的是思考，但往往没有思维没有前进，有的是担忧，设想某些境地，有的是游戏或者小说中画面的重构。

  其实，这和我一直希望实现的 inbox 理念不同。
  我尝试用 Emacs，把所有的事务都放在同一个平台进行处理，就是希望能够详尽管理所有的待办和想法，从头脑记忆变为外脑记忆。

  显然，inbox 还没有成功。

  不过，也不一定就是因为没有记录下来才不断的想。
  可以尝试把头脑中的想法逐个记录下来，看看是否能减少脑子中想的事情，以此来判断。

 <2021-03-20 Sat>
  inbox 确实可以减少脑中的胡思乱想。还有在发现自己想法开始扩散时，inbox 可以提醒，真正还没有做完的事情是哪些，有助于减少焦虑，提高注意力

* DONE 早起习惯
  CLOSED: [2021-03-20 Sat 16:29]
  :PROPERTIES:
  :创建:       [2021-02-23 Tue 23:59]
  :END:

早起做什么

打网球 7 点到 8 点的话，6点 50 分就要离开宿舍，6点 40 分就起床。所以起床时间暂定为 6 点 40，不打球就加 10 分钟冥想。

早起，不是为了起床之后的事可以慢慢做，而是要抓紧时间做想做的事比如打球，或者就正常工作
