* 论文写作
** 学位论文写作
*** 华科博士、硕士学位论文撰写规定

    摘要应该独立成文，致谢体现语言功底，这两个务必写好
    英文摘要不能直接用软件翻译，注意专业术语表达
    行间距一致，公式输入的变量和文本的区别

**** 基本要求

 - 掌握了坚实的基础理论和系统的专门知识： 体现在文献调研、国内外研究现状
 - 新的见解：理论创新，技术创新，效果提高
 - 从事科学研究工作或独立担负专门技能技术的能力：附件中的已发表论文和参与的项目（承担的工作）
 - 立论正确、推理严谨、文字简练、层次分明、说理透彻、数据真实可靠：不能拷贝改写
 - 阅读相关文献，综述部分对所读文献进行分析和综合：用自己的语言概括文献中的成果。在开始或结尾部分，一段或者两端，通过分析得出存在的问题，需要解决的问题
 - 学术术语、标点符号、缩写
 - 图要精选，切忌与文字或者表内容重复，避免没有意义的图：图的信息丰富、准确，禁忌常见图片的拷贝；过于简单的图不要；必要的说明

**** 题名

 不超过20个字，避免使用不常见的缩写词、字符和公式

**** 摘要（关键字）、目录、致谢

 内容--摘要，结构--目录，表达能力--致谢

***** 摘要

 - 不必分层次：首先，其次……
 - 背景、问题、成果、意义
 - 关键词：从大到小，从领域到技术，便于文献编目与查询
 - 英文摘要：不要直接软件翻译
 标准：当审稿人需要写评语时，可以直接在摘要部分找或者复制就可以

**** 正文
***** 绪论

 - 研究背景与意义, 国内外研究现状与分析, 研究内容与论文结构
 - 内容之间有严密的逻辑论证关系
 - 实事求是，客观真切，准确完备，合乎逻辑，层次分明，简练可读。工具等说明不需要
 - 格式：两端对齐、行间距1.25、公式、变量与文本输入的区别

***** 结论

 - 包括：总结与展望
 - 研究的问题

***** 致谢

 - 敏感信息，直接用xxx代替
 - 避免拷贝，避免胡言乱语

***** 参考文献

 - 按需引用
 - 按顺序引用
 - 格式：国际标准
 - 类型：图书，期刊，会议论文集，专利，学位论文
 - 脚注：网址等信息可以用脚注代替

*** 公式

 word中latex插件：TeXsword，Aurora
 ppt中latex插件：IguanaTex

* 2020新冠肺炎
** 2020疫情隔离期间讨论
*** 支部讨论

 - 对于世界体系过于乐观，实则脆弱

 - 对于人，过于黑暗，实则坚强

 例子：同学全家病重，无法送进医院，大家捐款帮忙送医院

 对于我们，非常好，认识到人的力量，认识到世界的不足，去努力改进吧

* World Nature
** 原理
** 理论的使用性

 一个理论，比如说牛顿定律，能解决什么问题，不是从数学上判断的；而是我们拿着这个理论去用，和实际对上了就说明它适用，什么时候对不上就说明它不适用了，这就是它的适用范围。

 很多实际问题，是没有办法也没有必要从理论上从数学上做出完备的解释的，往往我们不一定需要了解他的机理，只需要掌握他的规律就能加以利用。

 实际上CFD算出来的东西要判断它是否可靠，要么能和实验对上，要么能和不同算法算的结果对上；这本质上就是寻找和掌握规律的一种方法

* humanity

真正爱过你的女孩子，城府深到你无法想象。
她可以在第一次见你的时候余光扫到你的球鞋，知道你家并不是很富裕，然后不动声色地跟你说想吃那个平价料理店，好久没吃好想念。
她可以一边和你聊天一边套出来你喜欢的女生的类型，然后拿着模板照片去调整自己的装扮，让你不知不觉看她越来越顺眼。
她可以在你不知道如何开口道歉的时候发生一堆生活里的破事请你帮忙，今天是电脑坏了明天是猫找不到了后天是自行车被偷了，等你满头大汗忙完了才发现之前为了啥事儿闹别扭的来着你已经忘了。
她可以正好路过你那里，正好多买了很多水果和零食，正好让你分给同事，让你在宿舍里被众人起哄揶揄，宣告正主身份。
她可以打着请你辅导功课的名义，天天缠着你，催着你，让你不能再在宿舍偷懒，只能陪她在图书馆攻克你那头疼的四六级。
她可以恰好生来就与你有同样的饮食习惯，听同样的歌，看同样的动漫，玩同一个游戏。
她可以恰好认得你喜欢的明星和球队，听得懂与他有关的所有段子和梗，和你一起笑的前仰后合。
她可以不要房子不要彩礼，随便你给的起什么，就等着说一句「我愿意」。
她可以在闻到你身上她没有的那款香水味的时候，不动声色的检查你所有的社交平台账号，一眼看出所有的蛛丝马迹，试探着问你，最近是不是很累，要不要一起出去旅行。
她可以搜集全所有你对他不好的证据，但是在你抱着她恳求她原谅你的时候，一键清空，当做无事发生过，让你以为你做的十分周全，不露痕迹。
在你一次又一次欺骗她之后，她终于拂袖而去，从你的世界里消失的干干净净，这个时候你才能真正明白她的城府到底有多深。

原来没有她之后，你根本找不到自己的东西，你也不知道为什么每次你需要个什么东西她三分钟就能递给你，而你自己三个月也找不到那副耳机。
你所有的亲朋好友都喜欢她，他们总是要时不时在你耳朵念叨一两句，每一次提起，你的心都好像被人凌迟处刑，你耳边响起了她的声音：呵，XXX，这就是你的报应。
你再也找不到像她那样对你的女生，原来外面的小妖精一旦选择了在一起，就会变得比她还任性，暴躁，扭曲，而且吵架起来从不主动原谅你。
原来女生例假是这么痛的，她都没教会你如何给人关心。
你们谈了这么久，从来没有为她买过一次卫生经，分不清日用和夜用，更别提加长型和轻薄型。

你不知道除了多喝热水以外还可以说什么甜言蜜语哄女生开心，原来她从来不治你，就会让你失去真正撩妹的能力。
你不知道怎么给女生拍好看的照片，什么角度的侧颜更好看，什么姿势显得腿更长，别的女生拂袖而去，只有你愣愣地站在原地。
你以前以为自己的缺点是不够有钱，她走了以后你才会明白，在你们过去的这段爱情里，你最大的错，是不够有心。

而她，从头到尾都知道这一点，却到最后都没有拆穿你。

* 评论

言行一致的咖啡：闻到的和喝到的完全一致

* how to discuss AI
1. problem
2. idea: 算法，特征
3. motivation: 创新点:对旧方法的改进，对新领域的探索
4. dataset-->structure-->loss value
5. evaluation

